document.querySelector(".para").innerHTML = `
<span class="all_para" id="para_1">1 : পারা</span>
<span class="all_para" id="para_2">2 : পারা</span>
<span class="all_para" id="para_3">3 : পারা</span>
<span class="all_para" id="para_4">4 : পারা</span>
<span class="all_para" id="para_5">5 : পারা</span>
<span class="all_para" id="para_6">6 : পারা</span>
<span class="all_para" id="para_7">7 : পারা</span>
<span class="all_para" id="para_8">8 : পারা</span>
<span class="all_para" id="para_9">9 : পারা</span>
<span class="all_para" id="para_10">10 : পারা</span>
<span class="all_para" id="para_11">11 : পারা</span>
<span class="all_para" id="para_12">12 : পারা</span>
<span class="all_para" id="para_13">13 : পারা</span>
<span class="all_para" id="para_14">14 : পারা</span>
<span class="all_para" id="para_15">15 : পারা</span>
<span class="all_para" id="para_16">16 : পারা</span>
<span class="all_para" id="para_17">17 : পারা</span>
<span class="all_para" id="para_18">18 : পারা</span>
<span class="all_para" id="para_19">19 : পারা</span>
<span class="all_para" id="para_20">20 : পারা</span>
<span class="all_para" id="para_21">21 : পারা</span>
<span class="all_para" id="para_22">22 : পারা</span>
<span class="all_para" id="para_23">23 : পারা</span>
<span class="all_para" id="para_24">24 : পারা</span>
<span class="all_para" id="para_25">25 : পারা</span>
<span class="all_para" id="para_26">26 : পারা</span>
<span class="all_para" id="para_27">27 : পারা</span>
<span class="all_para" id="para_28">28 : পারা</span>
<span class="all_para" id="para_29">29 : পারা</span>
<span class="all_para" id="para_30">30 : পারা</span>`;