document.querySelector(".sura").innerHTML = `
                <span class="all_sura" id="sura-fatiha-1">1 : সূরা ফাতিহা</span>
                <span class="all_sura" id="sura-bakara-2">2 : সূরা বাকারা</span>
                <span class="all_sura" id="sura-al-imran-3">3 : সূরা আল ইমরান</span>
                <span class="all_sura" id="sura-nisa-4">4 : সূরা নিসা</span>
                <span class="all_sura" id="sura-maidati-5">5 : সূরা মায়িদাতি</span>
                <span class="all_sura" id="sura-anam-6">6 : সূরা আন-আম</span>
                <span class="all_sura" id="sura-araf-7">7 : সূরা আরাফ</span>
                <span class="all_sura" id="sura-angfal-8">8 : সূরা আংফাল</span>
                <span class="all_sura" id="sura-tawba-9">9 : সূরা তাওবা</span>
                <span class="all_sura" id="sura-iunuse-10">10 : সূরা ইউনুস</span>
                <span class="all_sura" id="sura-hud-11">11 : সূরা হুদ</span>
                <span class="all_sura" id="sura-iusuf-12">12 : সূরা ইউসুফ</span>
                <span class="all_sura" id="sura-radi-13">13 : সূরা রদি</span>
                <span class="all_sura" id="sura-ebrahim-14">14 : সূরা ইব্রাহিম</span>
                <span class="all_sura" id="sura-hijri-15">15 : সূরা হিজরী</span>
                <span class="all_sura" id="sura-nahli-16">16 : সূরা নাহলি</span>
                <span class="all_sura" id="sura-bani-israil-17">17 : সূরা বনী-ইসরাইল</span>
                <span class="all_sura" id="sura-kahfi-18">18 : সূরা কাহাফ</span>
                <span class="all_sura" id="sura-mariam-19">19 : সূরা মারিয়াম</span>
                <span class="all_sura" id="sura-toha-20">20 : সূরা তোহা</span>
                <span class="all_sura" id="sura-ambia-21">21 : সূরা আম্বিয়া</span>
                <span class="all_sura" id="sura-hajji-22">22 : সূরা হাজ্জি</span>
                <span class="all_sura" id="sura-muminuna-23">23 : সূরা মু-মিনুনা</span>
                <span class="all_sura" id="sura-nuri-24">24 : সূরা নুর</span>
                <span class="all_sura" id="sura-furqan-25">25 : সূরা ফুরকান</span>
                <span class="all_sura" id="sura-shuara-26">26 : সূরা শু-আরা</span>
                <span class="all_sura" id="sura-namli-27">27 : সূরা নামলি</span>
                <span class="all_sura" id="sura-kosasi-28">28 : সূরা কোসাস</span>
                <span class="all_sura" id="sura-angkabut-29">29 : সূরা আনকাবুত</span>
                <span class="all_sura" id="sura-rum-30">30 : সূরা রুম</span>
                <span class="all_sura" id="sura-lukman-31">31 : সূরা লুকমান</span>
                <span class="all_sura" id="sura-sajda-32">32 : সূরা সাজদাহ</span>
                <span class="all_sura" id="sura-ahjab-33">33 : সূরা আহযাব</span>
                <span class="all_sura" id="sura-sabai-34">34 : সূরা সাবায়ী</span>
                <span class="all_sura" id="sura-fatri-35">35 : সূরা ফাতরি</span>
                <span class="all_sura" id="sura-yisin-36">36 : সূরা ইয়াসিন</span>
                <span class="all_sura" id="sura-soffah-37">37 : সূরা সোফফাহ</span>
                <span class="all_sura" id="sura-swad-38">38 : সূরা সোয়াদ</span>
                <span class="all_sura" id="sura-jumari-39">39 : সূরা জুমারী</span>
                <span class="all_sura" id="sura-mu-mini-40">40 : সূরা মু-মিনি</span>
                <span class="all_sura" id="sura-hamim-sajda-41">41 : সূরা হামীম-সাজদাহ</span>
                <span class="all_sura" id="sura-shura-42">42 : সূরা শুরা</span>
                <span class="all_sura" id="sura-jukhrufi-43">43 : সূরা জুখরুফি</span>
                <span class="all_sura" id="sura-dukhan-44">44 : সূরা দুখান</span>
                <span class="all_sura" id="sura-jasiyati-45">45 : সূরা জাসিয়াতি</span>
                <span class="all_sura" id="sura-ahqafi-46">46 : সূরা আহকফি</span>
                <span class="all_sura" id="sura-muhammad-47">47 : সূরা মুহাম্মাদ</span>
                <span class="all_sura" id="sura-fathi-48">48 : সূরা ফাতহি</span>
                <span class="all_sura" id="sura-hujrat-49">49 : সূরা হুজুরাত</span>
                <span class="all_sura" id="sura-qafe-50">50 : সূরা কফ</span>
                <span class="all_sura" id="sura-jariyati-51">51 : সূরা ঝরিয়াতি</span>
                <span class="all_sura" id="sura-tur-52">52 : সূরা তুর</span>
                <span class="all_sura" id="sura-najmi-53">53 : সূরা নাজমি</span>
                <span class="all_sura" id="sura-qomar-54">54 : সূরা কমার</span>
                <span class="all_sura" id="sura-rahman-55">55 : সূরা রহমান</span>
                <span class="all_sura" id="sura-wakiyati-56">56 : সূরা ওয়াকিয়া</span>
                <span class="all_sura" id="sura-hadid-57">57 : সূরা হাদিদ</span>
                <span class="all_sura" id="sura-mujdalati-58">58 : সূরা মুজদালাতি</span>
                <span class="all_sura" id="sura-hashri-59">59 : সূরা হাশর</span>
                <span class="all_sura" id="sura-al-mumtahinati-60">60 : সূরা মুমতাহিন</span>
                <span class="all_sura" id="sura-soffi-61">61 : সূরা সফফি</span>
                <span class="all_sura" id="sura-jumati-62">62 : সূরা জুম-আতি</span>
                <span class="all_sura" id="sura-munafiquna-63">63 : সূরা মুনাফিকুন</span>
                <span class="all_sura" id="sura-tagabuni-64">64 : সূরা তাগাবুন</span>
                <span class="all_sura" id="sura-tolaq-65">65 : সূরা ত্বলাক</span>
                <span class="all_sura" id="sura-tahrim-66">66 : সূরা তাহরিম</span>
                <span class="all_sura" id="sura-mulk-67">67 : সূরা মুলক</span>
                <span class="all_sura" id="sura-kolam-68">68 : সূরা ক্কলাম</span>
                <span class="all_sura" id="sura-hakkoti-69">69 : সূরা হাক্কত</span>
                <span class="all_sura" id="sura-marij-70">70 : সূরা মা-রিজ</span>
                <span class="all_sura" id="sura-nuhi-71">71 : সূরা নু-হি</span>
                <span class="all_sura" id="sura-jin-72">72 : সূরা জিন</span>
                <span class="all_sura" id="sura-mujjammil-73">73 : সূরা মুজ্জাম্মিল</span>
                <span class="all_sura" id="sura-muddasir-74">74 : সূরা মুদ্দাসীর</span>
                <span class="all_sura" id="sura-kiyamati-75">75 : সূরা কিয়ামাহ</span>
                <span class="all_sura" id="sura-dahri-76">76 : সূরা দাহরি</span>
                <span class="all_sura" id="sura-mursalat-77">77 : সূরা মুরসালাত</span>
                <span class="all_sura" id="sura-naba-78">78 : সূরা নাবা</span>
                <span class="all_sura" id="sura-najiati-79">79 : সূরা নাজি-আত</span>
                <span class="all_sura" id="sura-abasa-80">80 : সূরা আবাসা</span>
                <span class="all_sura" id="sura-takbir-81">81 : সূরা তাকবীর</span>
                <span class="all_sura" id="sura-ingfitor-82">82 : সূরা ইনফিতূর</span>
                <span class="all_sura" id="sura-mutaffifin-83">83 : সূরা মুতাফিফিন</span>
                <span class="all_sura" id="sura-ingshikak-84">84 : সূরা ইনশিকক</span>
                <span class="all_sura" id="sura-buruj-85">85 : সূরা বুরুজ</span>
                <span class="all_sura" id="sura-torik-86">86 : সূরা তরিক</span>
                <span class="all_sura" id="sura-ala-87">87 : সূরা আয়া-লা</span>
                <span class="all_sura" id="sura-goshia-88">88 : সূরা গশিয়াহ</span>
                <span class="all_sura" id="sura-fajri-89">89 : সূরা ফজরি</span>
                <span class="all_sura" id="sura-balad-90">90 : সূরা বালাদ</span>
                <span class="all_sura" id="sura-shams-91">91 : সূরা শামসি</span>
                <span class="all_sura" id="sura-laili-92">92 : সূরা লাইলী</span>
                <span class="all_sura" id="sura-duha-93">93 : সূরা দুহা</span>
                <span class="all_sura" id="sura-alamnash-rah-94">94 : সূরা আলামনাশ-রহ</span>
                <span class="all_sura" id="sura-tin-95">95 : সূরা তিন</span>
                <span class="all_sura" id="sura-alak-96">96 : সূরা আলাক</span>
                <span class="all_sura" id="sura-kodr-97">97 : সূরা কোদর</span>
                <span class="all_sura" id="sura-bainah-98">98 : সূরা বাইয়্যিনাহ</span>
                <span class="all_sura" id="sura-jiljal-99">99 : সূরা জিল-জাল</span>
                <span class="all_sura" id="sura-adiat-100">100 : সূরা আদি-য়াত</span>
                <span class="all_sura" id="sura-koriah-101">101 : সূরা করিয়াহ</span>
                <span class="all_sura" id="sura-takasur-102">102 : সূরা তাকাসুর</span>
                <span class="all_sura" id="sura-asri-103">103 : সূরা আসরি</span>
                <span class="all_sura" id="sura-humajat-104">104 : সূরা হুমাজাত</span>
                <span class="all_sura" id="sura-fil-105">105 : সূরা ফিল</span>
                <span class="all_sura" id="sura-kuraish-106">106 : সূরা কোরাইশ</span>
                <span class="all_sura" id="sura-maun-107">107 : সূরা মাউন</span>
                <span class="all_sura" id="sura-kawsar-108">108 : সূরা কাওসার</span>
                <span class="all_sura" id="sura-kafirun-109">109 : সূরা কাফিরুন</span>
                <span class="all_sura" id="sura-nasri-110">110 : সূরা নাসরি</span>
                <span class="all_sura" id="sura-lahab-111">111 : সূরা লাহাব</span>
                <span class="all_sura" id="sura-ikhlas-112">112 : সূরা ইখলাস</span>
                <span class="all_sura" id="sura-falaq-113">113 : সূরা ফালাক</span>
                <span class="all_sura" id="sura-nas-114">114 : সূরা নাস</span>`;